In [3]:
import Processador as PC

In [4]:
#        CACHE       #
######################
#  CAPACIDADE EM kB  # 
c_capacity = 1
######################
#   NÚMERO DE VIAS   # 
c_vias = 2
######################
# PALAVRAS POR BLOCO #
c_palavras = 4

In [5]:
#  MEMÓRIA PRINCIPAL #
######################
# UNIDADE PARA O TAMANHO DA DRAM
# {1 = kB} {2 = MB} {3 = GB} {4 = TB} {...}
d_unity = 1
# CAPACIDADE PARA A DRAM NA UNIDADE DEFINIDA
d_capacity = 100

In [6]:
#    INSTRUÇÕES   #
# ESCREVER AS INSTRUÇÕES EM SEU VALOR DECIMAL EM UM VETOR
instrucoes = [2349338728, 2349401464, 2349469053, 2349532018, 2349607799, 17399840, 34113570, 19419178, 16801920, 16799874, 17410084, 17412133, 17414183, 134217743, 134217744, 201326606, 2886471784, 2886343780, 2886275684, 288423941, 65011720]

In [7]:
# INSTRUCOES DE TESTE
# LOAD >> 100011 00000 01000  0001000001101000 >> 2349338728 
# LOAD >> 100011 00000 01001  0000010101111000 >> 2349401464 
# LOAD >> 100011 00000 01010  0000110101111101 >> 2349469053 
# LOAD >> 100011 00000 01011  0000001101110010 >> 2349532018 
# LOAD >> 100011 00000 01100  0010101101110111 >> 2349607799 
# ADD  >> 000000 01000 01001 10000 00000 100000 >> 17399840
# SUB  >> 000000 10000 01000 10001 00000 100010 >> 34113570
# SLT  >> 000000 01001 01000 01010 00000 101010 >> 19419178
# SLL  >> 000000 01000 00000 01100 00010 000000 >> 16801920
# SRL  >> 000000 01000 00000 01011 00010 000010 >> 16799874
# AND  >> 000000 01000 01001 10101 00000 100100 >> 17410084
# OR   >> 000000 01000 01001 10110 00000 100101 >> 17412133
# NOR  >> 000000 01000 01001 10111 00000 100111 >> 17414183
# J    >> 000010 00000 00000 00000 00000 001111 >> 134217743
# J    >> 000010 00000 00000 00000 00000 010000 >> 134217744
# JAL  >> 000011 00000 00000 00000 00000 001110 >> 201326606
# STORE>> 101011 00000 01100  0001000001101000  >> 2886471784
# STORE>> 101011 00000 01010  0001110001100100  >> 2886343780
# STORE>> 101011 00000 01001  0001001001100100  >> 2886275684
# BEQ  >> 000100 01001 10001 00000 00000 000101 >> 288423941
# JR   >> 000000 11111 00000 00000 00000 001000 >> 65011720

#[2349338728, 2349401464, 2349469053, 2349532018, 2349607799, 17399840, 34113570, 19419178, 16801920, 16799874, 17410084, 17412133, 17414183, 134217743, 134217744, 201326606, 2886471784, 2886343780, 2886275684, 288423941, 65011720]

In [8]:
processador = PC.Processor(c_capacity, c_vias, c_palavras, d_unity, d_capacity, instrucoes)

In [9]:
print("DRAM")
processador.cache.dram.palavras

DRAM


[[1650671710, 1578655241, 3727233345, 4137768478],
 [3004286261, 2250485181, 3039145028, 865719872],
 [1659428468, 1782642896, 3583722472, 3930208214],
 [3070633422, 2114182390, 1851741045, 3959460628],
 [1691828662, 73509753, 2752444174, 1111910405],
 [840683749, 3563375141, 1048388657, 3522221632],
 [3820179848, 3897871440, 2828497077, 2878119441],
 [2600145462, 520174672, 1997216037, 687645803],
 [3151193623, 2438112719, 3403819845, 515907573],
 [967889596, 3472001663, 3005134187, 3444531760],
 [134371342, 3893748720, 41899287, 3054209049],
 [4168117556, 4284424454, 459448342, 1111739013],
 [1221897529, 979954256, 1530899625, 2274783610],
 [1504812196, 2827956506, 3603359094, 1567731551],
 [1192779920, 1885392250, 2131199238, 2786600235],
 [901683512, 3994913290, 728010581, 181636093],
 [217054757, 1158150287, 4000637806, 3417915524],
 [2110366454, 1481299733, 2130282416, 544615300],
 [729672830, 40771446, 3559305922, 2298534749],
 [2971369040, 1299412457, 2591300751, 4082854877],
 

In [10]:
len(processador.cache.dram.palavras)

6421

In [11]:
print("Endereco Limite DRAM")
processador.cache.rep_max

Endereco Limite DRAM


6399

In [12]:
processador.n_instrucoes

21

In [53]:
processador.load_instruction()

Foi realizado o load de uma instrução da DRAM >> + 50 ciclos
A instrucão BEQ (Branch if Equal) é realizada diretamente nos registradores, assim, há acréscimo de 1 nos ciclos


In [49]:
print("Ciclos")
print(processador.ciclos)
print("PC")
print(processador.pc)
print("Registradores")
print(processador.registradores.report())

Ciclos
1319
PC
19
Registradores
$zero >> { 0 }
$at >> { 0 }
$v0 >> { 0 } | $v1 >> { 0 }
$a0 >> { 0 } | $a1 >> { 0 } | $a2 >> { 0 } | $a3 >> { 0 }
$t0 >> { 88 } | $t1 >> { 126 } | $t2 >> { 0 } | $t3 >> { 22 } | $t4 >> { 352 }
$t5 >> { 0 } | $t6 >> { 0 } | $t7 >> { 0 } | $t8 >> { 0 } | $t9 >> { 0 }
$s0 >> { 214 } | $s1 >> { 126 } | $s2 >> { 0 } | $s3 >> { 0 }
$s4 >> { 0 } | $s5 >> { 88 } | $s6 >> { 126 } | $s7 >> { 4294967169 }
$k0 >> { 0 } | $k1 >> { 0 }
$gp >> { 0 }
$sp >> { 0 }
$fp >> { 0 }
$ra >> { 16 }
None


In [51]:
print("CONJUNTO 6 CACHE")
print(processador.cache.conjuntos[6])
print("LRU CONJUNTO 6 CACHE" , end=" -> ")
print(processador.cache.lru[6])

CONJUNTO 6 CACHE
[[6, 0, True, True, True, 9, [2802128844, 126, 485081208, 576126452]], [6, 1, True, True, True, 14, [3682531451, 0, 3486339068, 422404929]]]
LRU CONJUNTO 6 CACHE -> [1, 0]


In [39]:
print("CONJUNTO 23 CACHE")
print(processador.cache.conjuntos[23])
print("LRU CONJUNTO 23 CACHE" , end=" -> ")
print(processador.cache.lru[23])

CONJUNTO 23 CACHE
[[23, 0, True, False, True, 1, [1885269819, 186467107, 2809267738, 855136407]], [23, 1, True, False, True, 21, [597844378, 2123897321, 3663420535, 96259770]]]
LRU CONJUNTO 23 CACHE -> [1, 1]


In [52]:
print("BLOCO DRAM 262", end = " -> ")
print(processador.cache.dram.palavras[262])
print("BLOCO DRAM 87", end = " -> ")
print(processador.cache.dram.palavras[87])
print("BLOCO DRAM 215", end = " -> ")
print(processador.cache.dram.palavras[215])
print("BLOCO DRAM 55", end = " -> ")
print(processador.cache.dram.palavras[55])
print("BLOCO DRAM 695", end = " -> ")
print(processador.cache.dram.palavras[695])
print("BLOCO DRAM 454", end = " -> ")
print(processador.cache.dram.palavras[454])
print("BLOCO DRAM 294", end = " -> ")
print(processador.cache.dram.palavras[294])

BLOCO DRAM 262 -> [1887642396, 3757295337, 352, 1690437550]
BLOCO DRAM 87 -> [850250977, 1865262110, 3210255486, 704673392]
BLOCO DRAM 215 -> [398041494, 3578668488, 2559528753, 1695576636]
BLOCO DRAM 55 -> [1885269819, 186467107, 2809267738, 855136407]
BLOCO DRAM 695 -> [597844378, 2123897321, 3663420535, 96259770]
BLOCO DRAM 454 -> [3682531451, 3608838566, 3486339068, 422404929]
BLOCO DRAM 294 -> [2802128844, 1910034904, 485081208, 576126452]


BYTES             3        2        1        0      
PALAVRA EXEMPLO = 01010101 01010101 01010101 01010101

PALAVRAS   0    1    2    3
BLOCO = WORD WORD WORD WORD

LOAD 1
INDICE 6 -- TAG 8 -- PALAVRA 2 -- BYTE 0 -- BLOCO DRAM 262

LOAD 2
INDICE 23 -- TAG 2 -- PALAVRA 2 -- BYTE 0 -- BLOCO DRAM 87

LOAD 3
INDICE 23 -- TAG 6 -- PALAVRA 3 -- BYTE 1 -- BLOCO DRAM 215

LOAD 4
INDICE 23 -- TAG 1 -- PALAVRA 0 -- BYTE 2 -- BLOCO DRAM 55

LOAD 5
INDICE 23 -- TAG 21 -- PALAVRA 1 -- BYTE 3 -- BLOCO DRAM 695

STORE 1
INDICE 6 -- TAG 8 -- PALAVRA 2 -- BLOCO DRAM 262 -- $t4

STORE 2
INDICE 6 -- TAG 14 -- PALAVRA 1 -- BLOCO DRAM 454 -- $t2

STORE 3
INDICE 6 -- TAG 9 -- PALAVRA 1 -- BLOCO DRAM 294 -- $t1

In [54]:
processador.report()

INSTRUÇÕES
Ao todo foram realizadas 20 intruções, onde:
100.0% ou 20 foram executadas corretamente
0.0% ou 0 não puderam ser executadas corretamente

ACESSO A CACHE
Ao todo foram realizados 8 acessos a cache, onde:
12.5% ou 1 foram cache hit
87.5% ou 7 foram cache miss

